dist: trusty
sudo: false
group: beta
language: node_js
node_js:
  - "8"
jobs:
  include:
    - stage: test
      script:
        - set -e
        - npm run flow
        - npm run lint
        - npm run test
        - npm run coverage
    - stage: NPM release
      if: tag IS present
      script: echo 'Deploying to NPM...'
      before_deploy: npm run build
      deploy:
        provider: npm
        email: augusto.lemble@gmail.com
        skip_cleanup: true
        api_key: $NPM_TOKEN
        on:
          repo: windingtree/wt-js-libs
          tags: true
