dist: trusty
sudo: false
group: beta
language: node_js
node_js:
  - "8"
script:
  - set -e
  - npm run lint
  - npm run test-build
deploy:
  provider: npm
  email: augusto.lemble@gmail.com
  skip_cleanup: true
  api_key: $NPM_TOKEN
  on:
    repo: windingtree/wt-js-libs
    tags: true

